version: '3.2'
services:
    mysqldb:
        container_name: mysql
        ports:
            - "33306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        image: mysql/mysqldb
    wordpress:
        image: wordpress:latest
        container_name: wordpress
        ports:
            - "8000:80"
        environment:
            WORDPRESS_DB_HOST: mysql-server:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        depends_on:
            - mysqldb
